// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMAQKki6fSG5M753ovZXXyUwYd_AFV4tQ',
    appId: '1:340579925002:web:72ec63c62cb3ef545333f3',
    messagingSenderId: '340579925002',
    projectId: 'ubt-nkt',
    authDomain: 'ubt-nkt.firebaseapp.com',
    storageBucket: 'ubt-nkt.firebasestorage.app',
    measurementId: 'G-0TFXXHYPZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgWCJvAEKCMsMo1wTJ3uV4fK-jg3oXto8',
    appId: '1:340579925002:android:d2d8aac7472aeae85333f3',
    messagingSenderId: '340579925002',
    projectId: 'ubt-nkt',
    storageBucket: 'ubt-nkt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVFfmFKeoXRStCag_K7g2xmWg3QTQTnGc',
    appId: '1:340579925002:ios:0b6064a8bea841215333f3',
    messagingSenderId: '340579925002',
    projectId: 'ubt-nkt',
    storageBucket: 'ubt-nkt.firebasestorage.app',
    iosBundleId: 'com.example.ubtPbb',
  );
}
